var dados = {
  "login": "isabellateix",
  "id": 51347086,
  "node_id": "MDQ6VXNlcjUxMzQ3MDg2",
  "avatar_url": "https://avatars3.githubusercontent.com/u/51347086?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/isabellateix",
  "html_url": "https://github.com/isabellateix",
  "followers_url": "https://api.github.com/users/isabellateix/followers",
  "following_url": "https://api.github.com/users/isabellateix/following{/other_user}",
  "gists_url": "https://api.github.com/users/isabellateix/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/isabellateix/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/isabellateix/subscriptions",
  "organizations_url": "https://api.github.com/users/isabellateix/orgs",
  "repos_url": "https://api.github.com/users/isabellateix/repos",
  "events_url": "https://api.github.com/users/isabellateix/events{/privacy}",
  "received_events_url": "https://api.github.com/users/isabellateix/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Isabella Teixeira",
  "company": "POSSIBLE Brazil",
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Account Manager at POSSIBLE Brazil. Studying Front-End Development.",
  "public_repos": 7,
  "public_gists": 0,
  "followers": 1,
  "following": 6,
  "created_at": "2019-06-04T00:20:04Z",
  "updated_at": "2019-06-26T00:45:38Z" 
}